# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 08:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('cell_number', models.IntegerField(max_length=10)),
                ('ticket_number', models.CharField(max_length=20)),
                ('structure', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2016, 8, 5, 8, 4, 28, 270536, tzinfo=utc))),
            ],
        ),
    ]
